---
title: "Data Visualization"
author: "Haley Dunleavy"
date: "10/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data and packages
```{r load data and packages, warning = FALSE, message = FALSE}
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
  library(sf)
  library(ggmap)  # devtools::install_github("dkahle/ggmap")
```

```{r}
esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e",
                    method = "libcurl"),
                stringsAsFactors = FALSE)

head(esc)
```

# Annual escapement by Species and Region

```{r, results = "hide"}
esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-", 
           remove = FALSE) %>% 
  mutate(Year = as.numeric(Year))


annual_esc <- esc %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarise(total_esc = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Coho", "Pink", "Chum"))

head(annual_esc)
```
# Visualize Escapement

Total escapement by region and species
```{r, echo = FALSE}
ggplot(data = annual_esc,
       aes(x = Species, y = total_esc, fill = SASAP.Region)) + 
  geom_col()

```

Escapement over time by species and region
```{r, echo = FALSE, fig.height= 12, fig.width = 7}
my_theme <- theme_bw() +
  theme(legend.position = "bottom")

annual_plot <- ggplot(data = annual_esc, 
                      aes(x = Year, y = total_esc, color = Species)) + 
  geom_point() + 
  geom_line() +
  facet_wrap(~SASAP.Region, 
             scales = "free_y",
             ncol = 1) +
  my_theme
  


annual_plot

ggsave("figures/escapement.png", annual_plot, width = 12, height = 7, units = "in")
```

# Map of sampling locations

Created a table with unique sampling locations, lats and longs

```{r}
locations <- esc %>% 
  # pulls out unique rows of one or more columns
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
```

Sampling locations
```{r, echo = FALSE}
# package DT

datatable(locations)
```

```{r, echo = FALSE}
leaflet(locations) %>%
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location)
  

```

```{r}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```



# Alder latitudinal gradient sampling
```{r, echo = FALSE}
alder_sampling <- read.csv("~/Documents/Advisor.meetings/Summer2019/Alder/alder.site.coordinates.csv")

alder_sampling <- 
  alder_sampling %>% drop_na()

leaflet(alder_sampling) %>%
  addTiles() %>% 
  addCircleMarkers(lng = ~Longitude, lat=  ~Latitude, popup = ~(paste(alder_sampling$Name, alder_sampling$Notes)))

```

